import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  poweredByHeader: false,
  trailingSlash: true,
  async headers() {
    // Static assets only. Broad HTML Cache-Control on /:path* skipped —
    // risky with trailingSlash redirects on Next 16.3.6.
    return [
      {
        source: "/_next/static/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
      {
        source: "/og.png",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=86400, stale-while-revalidate=604800",
          },
        ],
      },
      {
        source: "/icon.svg",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=86400, stale-while-revalidate=604800",
          },
        ],
      },
      {
        source: "/:path*",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Permissions-Policy",
            value:
              "camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()",
          },
        ],
      },
    ];
  },
  async redirects() {
    return [
      { source: "/cute", destination: "/cute-kaomoji/", permanent: true },
      { source: "/cute/", destination: "/cute-kaomoji/", permanent: true },
      { source: "/cat", destination: "/cat-kaomoji/", permanent: true },
      { source: "/cat/", destination: "/cat-kaomoji/", permanent: true },
      { source: "/happy", destination: "/happy-kaomoji/", permanent: true },
      { source: "/happy/", destination: "/happy-kaomoji/", permanent: true },
      { source: "/crying", destination: "/crying-kaomoji/", permanent: true },
      { source: "/crying/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/cry", destination: "/crying-kaomoji/", permanent: true },
      { source: "/cry/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kawaii-emoticons", destination: "/cute-kaomoji/", permanent: true },
      { source: "/kawaii-emoticons/", destination: "/cute-kaomoji/", permanent: true },

      // Cry merges -> crying primary
      { source: "/cry-kaomoji", destination: "/crying-kaomoji/", permanent: true },
      { source: "/cry-kaomoji/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kaomoji-cry", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kaomoji-cry/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kaomoji-crying", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kaomoji-crying/", destination: "/crying-kaomoji/", permanent: true },
      // Copy-paste utility merges
      {
        source: "/copy-and-paste-kaomoji",
        destination: "/kaomoji-copy-paste/",
        permanent: true,
      },
      {
        source: "/copy-and-paste-kaomoji/",
        destination: "/kaomoji-copy-paste/",
        permanent: true,
      },
      {
        source: "/kaomoji-copy-and-paste",
        destination: "/kaomoji-copy-paste/",
        permanent: true,
      },
      {
        source: "/kaomoji-copy-and-paste/",
        destination: "/kaomoji-copy-paste/",
        permanent: true,
      },
      // Plural / alias -> hub
      { source: "/kaomojis", destination: "/", permanent: true },
      { source: "/kaomojis/", destination: "/", permanent: true },
      { source: "/kaomoji", destination: "/", permanent: true },
      { source: "/kaomoji/", destination: "/", permanent: true },
      // Common misspellings -> hub
      { source: "/kamoji", destination: "/", permanent: true },
      { source: "/kamoji/", destination: "/", permanent: true },
      { source: "/koamoji", destination: "/", permanent: true },
      { source: "/koamoji/", destination: "/", permanent: true },
      { source: "/kaoomoji", destination: "/", permanent: true },
      { source: "/kaoomoji/", destination: "/", permanent: true },
      { source: "/kaommoji", destination: "/", permanent: true },
      { source: "/kaommoji/", destination: "/", permanent: true },
      { source: "/kaamoji", destination: "/", permanent: true },
      { source: "/kaamoji/", destination: "/", permanent: true },
      { source: "/kaimoji", destination: "/", permanent: true },
      { source: "/kaimoji/", destination: "/", permanent: true },
      // Short synonym -> sad primary (recheck R3)
      { source: "/sad", destination: "/sad-kaomoji/", permanent: true },
      { source: "/sad/", destination: "/sad-kaomoji/", permanent: true },

      // Misspell gap
      { source: "/sad-kamoji", destination: "/sad-kaomoji/", permanent: true },
      { source: "/sad-kamoji/", destination: "/sad-kaomoji/", permanent: true },
      // Plural category aliases -> singular primaries (no thin pages)
      { source: "/cute-kaomojis", destination: "/cute-kaomoji/", permanent: true },
      { source: "/cute-kaomojis/", destination: "/cute-kaomoji/", permanent: true },
      { source: "/happy-kaomojis", destination: "/happy-kaomoji/", permanent: true },
      { source: "/happy-kaomojis/", destination: "/happy-kaomoji/", permanent: true },
      { source: "/cat-kaomojis", destination: "/cat-kaomoji/", permanent: true },
      { source: "/cat-kaomojis/", destination: "/cat-kaomoji/", permanent: true },
      { source: "/sad-kaomojis", destination: "/sad-kaomoji/", permanent: true },
      { source: "/sad-kaomojis/", destination: "/sad-kaomoji/", permanent: true },
      { source: "/crying-kaomojis", destination: "/crying-kaomoji/", permanent: true },
      { source: "/crying-kaomojis/", destination: "/crying-kaomoji/", permanent: true },
      // Singular / alt aliases for alt-head pages
      { source: "/japanese-emoticon", destination: "/japanese-emoticons/", permanent: true },
      { source: "/japanese-emoticon/", destination: "/japanese-emoticons/", permanent: true },
      { source: "/text-face", destination: "/text-faces/", permanent: true },
      { source: "/text-face/", destination: "/text-faces/", permanent: true },
      // Pagination: /page/1 -> bare category URL (permanent redirect)
      { source: "/cute-kaomoji/page/1", destination: "/cute-kaomoji/", permanent: true },
      { source: "/cute-kaomoji/page/1/", destination: "/cute-kaomoji/", permanent: true },
      { source: "/happy-kaomoji/page/1", destination: "/happy-kaomoji/", permanent: true },
      { source: "/happy-kaomoji/page/1/", destination: "/happy-kaomoji/", permanent: true },
      { source: "/cat-kaomoji/page/1", destination: "/cat-kaomoji/", permanent: true },
      { source: "/cat-kaomoji/page/1/", destination: "/cat-kaomoji/", permanent: true },
      { source: "/sad-kaomoji/page/1", destination: "/sad-kaomoji/", permanent: true },
      { source: "/sad-kaomoji/page/1/", destination: "/sad-kaomoji/", permanent: true },
      { source: "/crying-kaomoji/page/1", destination: "/crying-kaomoji/", permanent: true },
      { source: "/crying-kaomoji/page/1/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/japanese-emoticons/page/1", destination: "/japanese-emoticons/", permanent: true },
      { source: "/japanese-emoticons/page/1/", destination: "/japanese-emoticons/", permanent: true },
      { source: "/text-faces/page/1", destination: "/text-faces/", permanent: true },
      { source: "/text-faces/page/1/", destination: "/text-faces/", permanent: true },

      // Angry family: flat owners + nested/aliases -> flat (no dual indexable sets)
      { source: "/angry", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomojis", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomojis/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/table-flip", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/table-flip/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/tableflip", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/tableflip/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/tableflip-kaomoji", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/tableflip-kaomoji/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/fight", destination: "/fight-kaomoji/", permanent: true },
      { source: "/fight/", destination: "/fight-kaomoji/", permanent: true },
      { source: "/rage", destination: "/angry-kaomoji/", permanent: true },
      { source: "/rage/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/mad", destination: "/angry-kaomoji/", permanent: true },
      { source: "/mad/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/mad-kaomoji", destination: "/angry-kaomoji/", permanent: true },
      { source: "/mad-kaomoji/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/furious", destination: "/angry-kaomoji/", permanent: true },
      { source: "/furious/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/furious-kaomoji", destination: "/angry-kaomoji/", permanent: true },
      { source: "/furious-kaomoji/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/pout", destination: "/pout-kaomoji/", permanent: true },
      { source: "/pout/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/annoyed", destination: "/pout-kaomoji/", permanent: true },
      { source: "/annoyed/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/annoyed-kaomoji", destination: "/pout-kaomoji/", permanent: true },
      { source: "/annoyed-kaomoji/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/glare", destination: "/angry-kaomoji/", permanent: true },
      { source: "/glare/", destination: "/angry-kaomoji/", permanent: true },
      // Nested angry children (legacy) -> flat owners
      { source: "/angry-kaomoji/table-flip", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/table-flip/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/fight", destination: "/fight-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/fight/", destination: "/fight-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/rage", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/rage/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/pout", destination: "/pout-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/pout/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/glare", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/glare/", destination: "/angry-kaomoji/", permanent: true },
      // Multiline + generator aliases
      { source: "/multiline", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/multiline/", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/multi-line-kaomoji", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/multi-line-kaomoji/", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/generator", destination: "/kaomoji-generator/", permanent: true },
      { source: "/generator/", destination: "/kaomoji-generator/", permanent: true },
      { source: "/make-kaomoji", destination: "/kaomoji-generator/", permanent: true },
      { source: "/make-kaomoji/", destination: "/kaomoji-generator/", permanent: true },
      // Pagination page/1 -> bare
      { source: "/angry-kaomoji/page/1", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/page/1/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/table-flip-kaomoji/page/1", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/table-flip-kaomoji/page/1/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/fight-kaomoji/page/1", destination: "/fight-kaomoji/", permanent: true },
      { source: "/fight-kaomoji/page/1/", destination: "/fight-kaomoji/", permanent: true },
      { source: "/rage-kaomoji/page/1", destination: "/angry-kaomoji/", permanent: true },
      { source: "/rage-kaomoji/page/1/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/pout-kaomoji/page/1", destination: "/pout-kaomoji/", permanent: true },
      { source: "/pout-kaomoji/page/1/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/glare-kaomoji/page/1", destination: "/angry-kaomoji/", permanent: true },
      { source: "/glare-kaomoji/page/1/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/multiline-kaomoji/page/1", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/multiline-kaomoji/page/1/", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/rage-kaomoji", destination: "/angry-kaomoji/", permanent: true },
      { source: "/rage-kaomoji/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/glare-kaomoji", destination: "/angry-kaomoji/", permanent: true },
      { source: "/glare-kaomoji/", destination: "/angry-kaomoji/", permanent: true },

      // Heart / shy aliases (love + blush are chips/tags, not doorway pages)
      { source: "/love", destination: "/heart-kaomoji/", permanent: true },
      { source: "/love/", destination: "/heart-kaomoji/", permanent: true },
      { source: "/love-kaomoji", destination: "/heart-kaomoji/", permanent: true },
      { source: "/love-kaomoji/", destination: "/heart-kaomoji/", permanent: true },
      { source: "/kiss-kaomoji", destination: "/heart-kaomoji/", permanent: true },
      { source: "/kiss-kaomoji/", destination: "/heart-kaomoji/", permanent: true },
      { source: "/hug-kaomoji", destination: "/heart-kaomoji/", permanent: true },
      { source: "/hug-kaomoji/", destination: "/heart-kaomoji/", permanent: true },
      { source: "/heart", destination: "/heart-kaomoji/", permanent: true },
      { source: "/heart/", destination: "/heart-kaomoji/", permanent: true },
      { source: "/blush", destination: "/shy-kaomoji/", permanent: true },
      { source: "/blush/", destination: "/shy-kaomoji/", permanent: true },
      { source: "/blush-kaomoji", destination: "/shy-kaomoji/", permanent: true },
      { source: "/blush-kaomoji/", destination: "/shy-kaomoji/", permanent: true },
      { source: "/shy", destination: "/shy-kaomoji/", permanent: true },
      { source: "/shy/", destination: "/shy-kaomoji/", permanent: true },
      { source: "/embarrassed-kaomoji", destination: "/shy-kaomoji/", permanent: true },
      { source: "/embarrassed-kaomoji/", destination: "/shy-kaomoji/", permanent: true },
      { source: "/heart-kaomoji/page/1", destination: "/heart-kaomoji/", permanent: true },
      { source: "/heart-kaomoji/page/1/", destination: "/heart-kaomoji/", permanent: true },
      { source: "/shy-kaomoji/page/1", destination: "/shy-kaomoji/", permanent: true },
      { source: "/shy-kaomoji/page/1/", destination: "/shy-kaomoji/", permanent: true },

      // P2 animal + mood aliases (chip synonyms stay tags, not doorway pages)
      { source: "/bunny", destination: "/bunny-kaomoji/", permanent: true },
      { source: "/bunny/", destination: "/bunny-kaomoji/", permanent: true },
      { source: "/rabbit", destination: "/bunny-kaomoji/", permanent: true },
      { source: "/rabbit/", destination: "/bunny-kaomoji/", permanent: true },
      { source: "/rabbit-kaomoji", destination: "/bunny-kaomoji/", permanent: true },
      { source: "/rabbit-kaomoji/", destination: "/bunny-kaomoji/", permanent: true },
      { source: "/dog", destination: "/dog-kaomoji/", permanent: true },
      { source: "/dog/", destination: "/dog-kaomoji/", permanent: true },
      { source: "/puppy", destination: "/dog-kaomoji/", permanent: true },
      { source: "/puppy/", destination: "/dog-kaomoji/", permanent: true },
      { source: "/puppy-kaomoji", destination: "/dog-kaomoji/", permanent: true },
      { source: "/puppy-kaomoji/", destination: "/dog-kaomoji/", permanent: true },
      { source: "/shocked", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/shocked/", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/surprised", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/surprised/", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/surprised-kaomoji", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/surprised-kaomoji/", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/smug", destination: "/smug-kaomoji/", permanent: true },
      { source: "/smug/", destination: "/smug-kaomoji/", permanent: true },
      { source: "/sleepy", destination: "/sleepy-kaomoji/", permanent: true },
      { source: "/sleepy/", destination: "/sleepy-kaomoji/", permanent: true },
      { source: "/tired", destination: "/sleepy-kaomoji/", permanent: true },
      { source: "/tired/", destination: "/sleepy-kaomoji/", permanent: true },
      { source: "/tired-kaomoji", destination: "/sleepy-kaomoji/", permanent: true },
      { source: "/tired-kaomoji/", destination: "/sleepy-kaomoji/", permanent: true },
      { source: "/confused", destination: "/confused-kaomoji/", permanent: true },
      { source: "/confused/", destination: "/confused-kaomoji/", permanent: true },
      { source: "/bear", destination: "/bear-kaomoji/", permanent: true },
      { source: "/bear/", destination: "/bear-kaomoji/", permanent: true },
      { source: "/bunny-kaomoji/page/1", destination: "/bunny-kaomoji/", permanent: true },
      { source: "/bunny-kaomoji/page/1/", destination: "/bunny-kaomoji/", permanent: true },
      { source: "/dog-kaomoji/page/1", destination: "/dog-kaomoji/", permanent: true },
      { source: "/dog-kaomoji/page/1/", destination: "/dog-kaomoji/", permanent: true },
      { source: "/shocked-kaomoji/page/1", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/shocked-kaomoji/page/1/", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/smug-kaomoji/page/1", destination: "/smug-kaomoji/", permanent: true },
      { source: "/smug-kaomoji/page/1/", destination: "/smug-kaomoji/", permanent: true },
      { source: "/sleepy-kaomoji/page/1", destination: "/sleepy-kaomoji/", permanent: true },
      { source: "/sleepy-kaomoji/page/1/", destination: "/sleepy-kaomoji/", permanent: true },
      { source: "/confused-kaomoji/page/1", destination: "/confused-kaomoji/", permanent: true },
      { source: "/confused-kaomoji/page/1/", destination: "/confused-kaomoji/", permanent: true },
      { source: "/bear-kaomoji/page/1", destination: "/bear-kaomoji/", permanent: true },
      { source: "/bear-kaomoji/page/1/", destination: "/bear-kaomoji/", permanent: true },


      // Clear synonym -> canonical (audit pack A5; permanent 308/301). No speculative aliases.
      { source: "/kawaii-kaomoji", destination: "/cute-kaomoji/", permanent: true },
      { source: "/kawaii-kaomoji/", destination: "/cute-kaomoji/", permanent: true },
      { source: "/japanese-kaomoji", destination: "/japanese-emoticons/", permanent: true },
      { source: "/japanese-kaomoji/", destination: "/japanese-emoticons/", permanent: true },
      { source: "/emoticons", destination: "/japanese-emoticons/", permanent: true },
      { source: "/emoticons/", destination: "/japanese-emoticons/", permanent: true },
      { source: "/kaomoji-faces", destination: "/text-faces/", permanent: true },
      { source: "/kaomoji-faces/", destination: "/text-faces/", permanent: true },
      { source: "/textface", destination: "/text-faces/", permanent: true },
      { source: "/textface/", destination: "/text-faces/", permanent: true },
      { source: "/textfaces", destination: "/text-faces/", permanent: true },
      { source: "/textfaces/", destination: "/text-faces/", permanent: true },
      { source: "/copy-paste-kaomoji", destination: "/kaomoji-copy-paste/", permanent: true },
      { source: "/copy-paste-kaomoji/", destination: "/kaomoji-copy-paste/", permanent: true },
      { source: "/lenny-face", destination: "/text-faces/", permanent: true },
      { source: "/lenny-face/", destination: "/text-faces/", permanent: true },
      { source: "/lenny", destination: "/text-faces/", permanent: true },
      { source: "/lenny/", destination: "/text-faces/", permanent: true },
      { source: "/shrug", destination: "/text-faces/", permanent: true },
      { source: "/shrug/", destination: "/text-faces/", permanent: true },
      { source: "/ascii-art", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/ascii-art/", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/ascii-kaomoji", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/ascii-kaomoji/", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/surprise-kaomoji", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/surprise-kaomoji/", destination: "/shocked-kaomoji/", permanent: true },
      { source: "/neko-kaomoji", destination: "/cat-kaomoji/", permanent: true },
      { source: "/neko-kaomoji/", destination: "/cat-kaomoji/", permanent: true },
      { source: "/flip-table", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/flip-table/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/punch-kaomoji", destination: "/fight-kaomoji/", permanent: true },
      { source: "/punch-kaomoji/", destination: "/fight-kaomoji/", permanent: true },
      { source: "/create-kaomoji", destination: "/kaomoji-generator/", permanent: true },
      { source: "/create-kaomoji/", destination: "/kaomoji-generator/", permanent: true },

    ];
  },
};

export default nextConfig;