import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  poweredByHeader: false,
  trailingSlash: true,
  async redirects() {
    return [
      { source: "/cute", destination: "/cute-kaomoji/", permanent: true },
      { source: "/cute/", destination: "/cute-kaomoji/", permanent: true },
      { source: "/cat", destination: "/cat-kaomoji/", permanent: true },
      { source: "/cat/", destination: "/cat-kaomoji/", permanent: true },
      { source: "/happy", destination: "/happy-kaomoji/", permanent: true },
      { source: "/happy/", destination: "/happy-kaomoji/", permanent: true },
      { source: "/crying", destination: "/crying-kaomoji/", permanent: true },
      { source: "/crying/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/cry", destination: "/crying-kaomoji/", permanent: true },
      { source: "/cry/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kawaii-emoticons", destination: "/cute-kaomoji/", permanent: true },
      { source: "/kawaii-emoticons/", destination: "/cute-kaomoji/", permanent: true },

      // Cry merges -> crying primary
      { source: "/cry-kaomoji", destination: "/crying-kaomoji/", permanent: true },
      { source: "/cry-kaomoji/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kaomoji-cry", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kaomoji-cry/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kaomoji-crying", destination: "/crying-kaomoji/", permanent: true },
      { source: "/kaomoji-crying/", destination: "/crying-kaomoji/", permanent: true },
      // Copy-paste utility merges
      {
        source: "/copy-and-paste-kaomoji",
        destination: "/kaomoji-copy-paste/",
        permanent: true,
      },
      {
        source: "/copy-and-paste-kaomoji/",
        destination: "/kaomoji-copy-paste/",
        permanent: true,
      },
      {
        source: "/kaomoji-copy-and-paste",
        destination: "/kaomoji-copy-paste/",
        permanent: true,
      },
      {
        source: "/kaomoji-copy-and-paste/",
        destination: "/kaomoji-copy-paste/",
        permanent: true,
      },
      // Plural / alias -> hub
      { source: "/kaomojis", destination: "/", permanent: true },
      { source: "/kaomojis/", destination: "/", permanent: true },
      { source: "/kaomoji", destination: "/", permanent: true },
      { source: "/kaomoji/", destination: "/", permanent: true },
      // Common misspellings -> hub
      { source: "/kamoji", destination: "/", permanent: true },
      { source: "/kamoji/", destination: "/", permanent: true },
      { source: "/koamoji", destination: "/", permanent: true },
      { source: "/koamoji/", destination: "/", permanent: true },
      { source: "/kaoomoji", destination: "/", permanent: true },
      { source: "/kaoomoji/", destination: "/", permanent: true },
      { source: "/kaommoji", destination: "/", permanent: true },
      { source: "/kaommoji/", destination: "/", permanent: true },
      { source: "/kaamoji", destination: "/", permanent: true },
      { source: "/kaamoji/", destination: "/", permanent: true },
      { source: "/kaimoji", destination: "/", permanent: true },
      { source: "/kaimoji/", destination: "/", permanent: true },
      // Misspell gap
      { source: "/sad-kamoji", destination: "/sad-kaomoji/", permanent: true },
      { source: "/sad-kamoji/", destination: "/sad-kaomoji/", permanent: true },
      // Plural category aliases -> singular primaries (no thin pages)
      { source: "/cute-kaomojis", destination: "/cute-kaomoji/", permanent: true },
      { source: "/cute-kaomojis/", destination: "/cute-kaomoji/", permanent: true },
      { source: "/happy-kaomojis", destination: "/happy-kaomoji/", permanent: true },
      { source: "/happy-kaomojis/", destination: "/happy-kaomoji/", permanent: true },
      { source: "/cat-kaomojis", destination: "/cat-kaomoji/", permanent: true },
      { source: "/cat-kaomojis/", destination: "/cat-kaomoji/", permanent: true },
      { source: "/sad-kaomojis", destination: "/sad-kaomoji/", permanent: true },
      { source: "/sad-kaomojis/", destination: "/sad-kaomoji/", permanent: true },
      { source: "/crying-kaomojis", destination: "/crying-kaomoji/", permanent: true },
      { source: "/crying-kaomojis/", destination: "/crying-kaomoji/", permanent: true },
      // Singular / alt aliases for alt-head pages
      { source: "/japanese-emoticon", destination: "/japanese-emoticons/", permanent: true },
      { source: "/japanese-emoticon/", destination: "/japanese-emoticons/", permanent: true },
      { source: "/text-face", destination: "/text-faces/", permanent: true },
      { source: "/text-face/", destination: "/text-faces/", permanent: true },
      // Pagination: /page/1 -> bare category URL (permanent redirect)
      { source: "/cute-kaomoji/page/1", destination: "/cute-kaomoji/", permanent: true },
      { source: "/cute-kaomoji/page/1/", destination: "/cute-kaomoji/", permanent: true },
      { source: "/happy-kaomoji/page/1", destination: "/happy-kaomoji/", permanent: true },
      { source: "/happy-kaomoji/page/1/", destination: "/happy-kaomoji/", permanent: true },
      { source: "/cat-kaomoji/page/1", destination: "/cat-kaomoji/", permanent: true },
      { source: "/cat-kaomoji/page/1/", destination: "/cat-kaomoji/", permanent: true },
      { source: "/sad-kaomoji/page/1", destination: "/sad-kaomoji/", permanent: true },
      { source: "/sad-kaomoji/page/1/", destination: "/sad-kaomoji/", permanent: true },
      { source: "/crying-kaomoji/page/1", destination: "/crying-kaomoji/", permanent: true },
      { source: "/crying-kaomoji/page/1/", destination: "/crying-kaomoji/", permanent: true },
      { source: "/japanese-emoticons/page/1", destination: "/japanese-emoticons/", permanent: true },
      { source: "/japanese-emoticons/page/1/", destination: "/japanese-emoticons/", permanent: true },
      { source: "/text-faces/page/1", destination: "/text-faces/", permanent: true },
      { source: "/text-faces/page/1/", destination: "/text-faces/", permanent: true },

      // Angry family: flat owners + nested/aliases -> flat (no dual indexable sets)
      { source: "/angry", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomojis", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomojis/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/table-flip", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/table-flip/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/tableflip", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/tableflip/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/tableflip-kaomoji", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/tableflip-kaomoji/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/fight", destination: "/fight-kaomoji/", permanent: true },
      { source: "/fight/", destination: "/fight-kaomoji/", permanent: true },
      { source: "/rage", destination: "/angry-kaomoji/", permanent: true },
      { source: "/rage/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/mad", destination: "/angry-kaomoji/", permanent: true },
      { source: "/mad/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/mad-kaomoji", destination: "/angry-kaomoji/", permanent: true },
      { source: "/mad-kaomoji/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/furious", destination: "/angry-kaomoji/", permanent: true },
      { source: "/furious/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/furious-kaomoji", destination: "/angry-kaomoji/", permanent: true },
      { source: "/furious-kaomoji/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/pout", destination: "/pout-kaomoji/", permanent: true },
      { source: "/pout/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/annoyed", destination: "/pout-kaomoji/", permanent: true },
      { source: "/annoyed/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/annoyed-kaomoji", destination: "/pout-kaomoji/", permanent: true },
      { source: "/annoyed-kaomoji/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/glare", destination: "/angry-kaomoji/", permanent: true },
      { source: "/glare/", destination: "/angry-kaomoji/", permanent: true },
      // Nested angry children (legacy) -> flat owners
      { source: "/angry-kaomoji/table-flip", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/table-flip/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/fight", destination: "/fight-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/fight/", destination: "/fight-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/rage", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/rage/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/pout", destination: "/pout-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/pout/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/glare", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/glare/", destination: "/angry-kaomoji/", permanent: true },
      // Multiline + generator aliases
      { source: "/multiline", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/multiline/", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/multi-line-kaomoji", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/multi-line-kaomoji/", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/generator", destination: "/kaomoji-generator/", permanent: true },
      { source: "/generator/", destination: "/kaomoji-generator/", permanent: true },
      { source: "/make-kaomoji", destination: "/kaomoji-generator/", permanent: true },
      { source: "/make-kaomoji/", destination: "/kaomoji-generator/", permanent: true },
      // Pagination page/1 -> bare
      { source: "/angry-kaomoji/page/1", destination: "/angry-kaomoji/", permanent: true },
      { source: "/angry-kaomoji/page/1/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/table-flip-kaomoji/page/1", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/table-flip-kaomoji/page/1/", destination: "/table-flip-kaomoji/", permanent: true },
      { source: "/fight-kaomoji/page/1", destination: "/fight-kaomoji/", permanent: true },
      { source: "/fight-kaomoji/page/1/", destination: "/fight-kaomoji/", permanent: true },
      { source: "/rage-kaomoji/page/1", destination: "/angry-kaomoji/", permanent: true },
      { source: "/rage-kaomoji/page/1/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/pout-kaomoji/page/1", destination: "/pout-kaomoji/", permanent: true },
      { source: "/pout-kaomoji/page/1/", destination: "/pout-kaomoji/", permanent: true },
      { source: "/glare-kaomoji/page/1", destination: "/angry-kaomoji/", permanent: true },
      { source: "/glare-kaomoji/page/1/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/multiline-kaomoji/page/1", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/multiline-kaomoji/page/1/", destination: "/multiline-kaomoji/", permanent: true },
      { source: "/rage-kaomoji", destination: "/angry-kaomoji/", permanent: true },
      { source: "/rage-kaomoji/", destination: "/angry-kaomoji/", permanent: true },
      { source: "/glare-kaomoji", destination: "/angry-kaomoji/", permanent: true },
      { source: "/glare-kaomoji/", destination: "/angry-kaomoji/", permanent: true },


    ];
  },
};

export default nextConfig;